spring:
  application:
    name: awesome-choice-spider
  datasource:
    username: fan
    password: 123456
#    url: jdbc:derby:database;create=true
    url: jdbc:derby://localhost:1527/database;create=true
    driver-class-name: org.apache.derby.jdbc.ClientDriver
#    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  sql:
    init:
      mode: always
      continue-on-error: true

  jpa:
    show-sql: false
    database: derby
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false   #缓存，如果要热部署设置为false
    prefix: classpath:/templates/  #静态页面前置目录
    check-template-location: true  #本地模板检查
    suffix: .html  #页面后缀
    encoding: UTF-8  #页面编码
    servlet:
      content-type: text/html  #页面类型
    mode: HTML  #页面模式，其实可以设置为HTML5、LEGACYHTML5（非严格检查格式，这个还需要其他包引入）
  mvc:
    static-path-pattern: /**  #静态资源父级路径
  web:
    resources:
      static-locations: classpath:/static/  #静态资源映射目录

#management:
#  endpoint:
#    shutdown:
#      enabled: true
#  server:
#    address: 127.0.0.1
#    port: 8000
#  endpoints:
#    web:
#      base-path: /ops
#      path-mapping:
#        shutdown: shutdown
#      exposure:
#        include: info, health, shutdown

#logging:
#  level:
#    root: debug
server:
  port: 8080
