CREATE INDEX IDX__RESULT_STOCK on RESULT (stock);
ALTER TABLE RESULT DROP CONSTRAINT IDX_REQUEST_ID;
CREATE INDEX IDX__SEARCH_BY_CODE_SOURCE_STOCK on SEARCH_BY_CODE_SOURCE (stock);
CREATE INDEX IDX_SEARCH_BY_CODE_SOURCE_REQUEST_ID on SEARCH_BY_CODE_SOURCE (request_id);
CREATE INDEX IDX_SEARCH_BY_CODE_SOURCE_YEAR on SEARCH_BY_CODE_SOURCE ("year");
